env:
  es6: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  "@typescript-eslint/ban-ts-comment": 0
  brace-style:
    - warn
    - 1tbs
  camelcase: warn
  comma-dangle:
    - warn
    - always-multiline
  comma-style:
    - error
    - last
  complexity:
    - error
    - 10
  curly: warn
  eol-last:
    - error
    - always
  id-length:
    - warn
  max-lines: error
  max-params:
    - warn
    - 5
  no-duplicate-imports: error
  no-eq-null: error
  eqeqeq:
    - warn
    - smart
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-shadow: off
  "@typescript-eslint/no-shadow": error
  no-undefined: error
  no-empty-function: off
  "@typescript-eslint/no-empty-function": warn
  no-extend-native: error
  no-param-reassign: warn
  no-unused-expressions: warn
  no-useless-concat: warn
  no-label-var: warn
  no-use-before-define: error
  no-const-assign: error
  no-useless-constructor: warn
  no-useless-rename: warn
  no-warning-comments:
    - warn
    - location: anywhere
      terms:
        - todo
        - fixme
  prefer-promise-reject-errors: error
  semi:
    - warn
    - always
  linebreak-style:
    - warn
    - unix
