---
parameters:
  logger:
    level: debug

  s3:
    region: us-east-1
    endpoint: null
    buckets:
      raw: raw

  eventbridge:
    region: us-east-1
    endpoint: null
    name: nonsense
    enabled: false

  dynamoDb:
    region: us-east-1
    endpoint: null
    tables:
      report: nonsense-table

