export const Status = {
	STARTED: 'STARTED',
	COMPLETED: 'COMPLETED',
	ERROR: 'ERROR',
	SHEET_LOADED: 'SHEET_LOADED',
	SHEET_PARSED: 'SHEET_PARSED',
	SHEET_VALIDATED: 'SHEET_VALIDATED',
	SHEET_TRANSFORMED: 'SHEET_TRANSFORMED',
};
